import{S as h,a as b,i as c}from"./assets/vendor--6n4cVRZ.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const u=document.querySelector(".gallery"),i=document.querySelector(".loader"),f=document.querySelector("#load-btn");let L=new h(".gallery a",{captionsData:"alt",captionDelay:250});async function m(r){const s=r.map(({webformatURL:o,largeImageURL:n,tags:e,likes:t,views:a,comments:y,downloads:g})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${n}">
          <img class="gallery-image" src="${o}" alt="${e}" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${t}</p>
          <p class="info-item"><b>Views</b> ${a}</p>
          <p class="info-item"><b>Comments</b> ${y}</p>
          <p class="info-item"><b>Downloads</b> ${g}</p>
        </div>
      </li>`).join("");u.insertAdjacentHTML("beforeend",s),L.refresh()}function w(){u.innerHTML=""}function S(){i&&i.classList.add("is-open")}function q(){i&&i.classList.remove("is-open")}function P(){f.classList.add("is-open")}function v(){f.classList.remove("is-open")}const $="54668130-3dbf133d1de2adf3be7a098c3",x="https://pixabay.com/api/",d=document.querySelector("#load-btn");let l=1;async function p(r){const s={key:$,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,_page:l};try{return(await b.get(x,{params:s})).data}catch(o){throw console.error("Info about error",o),o}}d.addEventListener("click",async()=>{try{const r=await p();m(r.hits),l+=1,l>1&&(d.textContent="Load more")}catch(r){console.log(r)}});const B=document.querySelector(".form");B.addEventListener("submit",async r=>{r.preventDefault();const s=r.currentTarget.elements["search-text"].value.trim();if(!s){c.warning({message:"Search field cannot be empty!"});return}w(),v(),S();try{const o=await p(s);o.hits.length===0?c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(m(o.hits),P())}catch{c.error({message:"Something went wrong. Please try again."})}finally{q(),r.target.reset()}});
//# sourceMappingURL=index.js.map
