import{a as b,S as L,i as d}from"./assets/vendor--6n4cVRZ.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const w="54668130-3dbf133d1de2adf3be7a098c3",S="https://pixabay.com/api/";async function f(r,o=1){const a={key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};try{return(await b.get(S,{params:a})).data}catch(s){throw console.error("Info about error",s),s}}const m=document.querySelector(".gallery"),l=document.querySelector(".loader"),p=document.querySelector("#load-btn");let q=new L(".gallery a",{captionsData:"alt",captionDelay:250});async function y(r){const o=r.map(({webformatURL:a,largeImageURL:s,tags:e,likes:t,views:n,comments:g,downloads:h})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s}">
          <img class="gallery-image" src="${a}" alt="${e}" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${t}</p>
          <p class="info-item"><b>Views</b> ${n}</p>
          <p class="info-item"><b>Comments</b> ${g}</p>
          <p class="info-item"><b>Downloads</b> ${h}</p>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",o),q.refresh()}function v(){m.innerHTML=""}function P(){l&&l.classList.add("is-open")}function B(){l&&l.classList.remove("is-open")}function $(){p.classList.add("is-open")}function x(){p.classList.remove("is-open")}const u=document.querySelector("#load-btn"),E=document.querySelector(".form");let c="",i=1;u.addEventListener("click",async()=>{try{i+=1;const r=await f(c,i);y(r.hits),i+=1;const a=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:a*3,behavior:"smooth"}),i>1&&(u.textContent="Load more")}catch(r){console.log(r)}});E.addEventListener("submit",async r=>{if(r.preventDefault(),c=r.currentTarget.elements["search-text"].value.trim(),!c){d.warning({message:"Search field cannot be empty!"});return}v(),x(),P();try{const o=await f(c,i);o.hits.length===0?d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(y(o.hits),$())}catch{d.error({message:"Something went wrong. Please try again."})}finally{B(),r.target.reset()}});
//# sourceMappingURL=index.js.map
