import{a as L,S as w,i as c}from"./assets/vendor--6n4cVRZ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const S="54668130-3dbf133d1de2adf3be7a098c3",v="https://pixabay.com/api/";async function f(r,t=1){const a={key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};try{return(await L.get(v,{params:a})).data}catch(s){throw console.error("Info about error",s),s}}const m=document.querySelector(".gallery"),u=document.querySelector(".loader"),y=document.querySelector("#load-btn");let P=new w(".gallery a",{captionsData:"alt",captionDelay:250});async function g(r){const t=r.map(({webformatURL:a,largeImageURL:s,tags:e,likes:o,views:i,comments:p,downloads:b})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s}">
          <img class="gallery-image" src="${a}" alt="${e}" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${o}</p>
          <p class="info-item"><b>Views</b> ${i}</p>
          <p class="info-item"><b>Comments</b> ${p}</p>
          <p class="info-item"><b>Downloads</b> ${b}</p>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",t),P.refresh()}function q(){m.innerHTML=""}function B(){u&&u.classList.add("is-open")}function $(){u&&u.classList.remove("is-open")}function h(){y.classList.add("is-open")}function d(){y.classList.remove("is-open")}const M=document.querySelector("#load-btn"),E=document.querySelector(".form");let l="",n=1;M.addEventListener("click",async()=>{d();try{n+=1;const r=await f(l,n);g(r.hits),n+=1;const a=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"});const s=Math.ceil(r.totalHits/15);n>=s?(d(),c.info({message:"We're sorry, but you've reached the end of search results."})):h()}catch(r){console.log(r)}});E.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.currentTarget.elements["search-text"].value.trim(),!l){c.warning({message:"Search field cannot be empty!"});return}n=1,q(),d(),B();try{const t=await f(l,n);if(t.hits.length===0)c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});else{g(t.hits);const a=Math.ceil(t.totalHits/15);n<a?h():c.info({message:"We're sorry, but you've reached the end of search results."})}}catch(t){console.log(t),c.error({message:"Something went wrong. Please try again."})}finally{$(),r.target.reset()}});
//# sourceMappingURL=index.js.map
